apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: ec2-instance-2
  namespace: default
spec:
  networkInterfaces:
    - deviceIndex: 0
  imageID: ami-05842291b9a0bd79f  # Example Amazon Linux 2 AMI ID
  instanceType: t2.micro
  subnetID: subnet-0dd40057437e9bd30  # Replace with your VPC Subnet ID
  securityGroupIDs:
    - sg-0d3ae66a07afde7c8  # Replace with your security group ID
  keyName: argo-window  # Optional: Replace with your EC2 KeyPair name
  minCount: 1  # Minimum number of instances to launch
  maxCount: 1  # Maximum number of instances to launch
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 8  # Volume size in GB
        volumeType: gp3  # General Purpose SSD
  tags:
    - key: Name
      value: ec2-instance-2
    - key: Environment
      value: dev
  monitoring:  # Add this line to enable detailed monitoring
    enabled: true  # Set to true to enable detailed monitoring
