apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: ec2-instance-5
spec:
  imageID: $INSTANCE_AMI_ID
  instanceType: $INSTANCE_TYPE
  subnetID: $INSTANCE_SUBNET_ID
  tags:
    - key: $INSTANCE_TAG_KEY
      value: $INSTANCE_TAG_VAL
