apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: $DB_INSTANCE_ID
spec:
  allocatedStorage: 5
  # Disable automated backups since it adds time to the provisioning
  # workflow...
  backupRetentionPeriod: 0
  dbInstanceClass: db.t3.micro
  engine: postgres
  engineVersion: "14.9"
  masterUsername: admin
  masterUserPassword:
    namespace: default
    name: rds-credentials-secret
    key: password
  multiAZ: false
  tags:
    - key: environment
      value: dev
