apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{ .Values.rds.dbInstanceIdentifier }}
  namespace: default
spec:
  dbInstanceIdentifier: {{ .Values.rds.dbInstanceIdentifier | quote }}
  dbInstanceClass: {{ .Values.rds.dbInstanceClass | quote }}
  engine: {{ .Values.rds.engine | quote }}
  masterUsername: {{ .Values.rds.username | quote }}
  masterUserPassword:
    namespace: default
    name: rds
    key: password
  allocatedStorage: {{ .Values.rds.allocatedStorage }}
  backupRetentionPeriod: {{ .Values.rds.backupRetentionPeriod }}
  publiclyAccessible: false
  vpcSecurityGroupIDs:
    - {{ .Values.rds.id }}
  dbSubnetGroupName: {{ .Values.rds.subnetGroupName | quote }}
