apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: "argo-test1"
  namespace: default
spec:
  name: "argo-test1"
  description: {{ .Values.securityGroupRDS.description | quote }}
  vpcID: {{ .Values.vpcID | quote }}
  ingressRules:
    {{- range .Values.securityGroupRDS.ingressRules }}
    - fromPort: {{ .fromPort }}
      toPort: {{ .toPort }}
      ipProtocol: {{ .ipProtocol | quote }}
      ipRanges:  # Use ipRanges if you're specifying CIDR blocks
        - cidrIP: {{ .cidrIP | quote }}
          description: {{ .description | quote }}
    {{- end }}
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: tcp
      ipRanges:
        - cidrIP: "10.0.0.0/8"
          description: "Allow all outbound traffic"
