apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: "argo-test2"
  namespace: default
spec:
  name: "argo-test2"
  description: "Allow traffic from specific CIDR range"
  vpcID: "vpc-021f9a2abf0532d92"
  ingressRules:
    - fromPort: 80
      toPort: 95
      ipProtocol: tcp
      ipRanges:
        - cidrIP: "10.0.0.0/8"
          description: "Allow in traffic"
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: tcp
      ipRanges:
        - cidrIP: "10.0.0.0/8"
          description: "Allow all outbound traffic"
