apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.4.0
        args:
          - --repo=https://github.com/moti-cohen/argo.git
          - --branch=main
          - --root=/workspace
          - --wait=10
        volumeMounts:
          - mountPath: /workspace
            name: workspace
      - name: file-monitor
        image: busybox
        command:
          - /bin/sh
        args:
          - -c
          - |
            while true; do
              sleep 10 &&
              if [ "$(md5sum /workspace/* | md5sum)" != "$(cat /workspace/.last_md5sum)" ]; then
                md5sum /workspace/* | md5sum > /workspace/.last_md5sum &&
                kubectl delete job terraform-job --ignore-not-found &&
                kubectl apply -f /workspace/job.yaml;
              fi;
            done
        volumeMounts:
          - mountPath: /workspace
            name: workspace
      volumes:
      - name: workspace
        emptyDir: {}

