apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
          - /bin/sh
        args:
          - -c
          - |
            rm -rf /workspace/* &&
            git clone https://github.com/moti-cohen/argo.git /workspace &&
            cd /workspace/template/ec2 &&
            terraform init &&
            terraform apply -auto-approve
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        emptyDir: {}
