apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/refresh: "true"  # Forces ArgoCD to refresh and detect changes
  labels:
    commitHash: "{{git_commit_hash}}"  # Use a dynamic label to trigger job update when commit changes
spec:
  template:
    metadata:
      labels:
        app: terraform-job
    spec:
      serviceAccountName: terraform-deploy-sa
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
          - /bin/sh
        args:
          - -c
          - |
            rm -rf /workspace/* &&
            git clone https://github.com/moti-cohen/argo.git /workspace &&
            cd /workspace/template/ec2 &&
            terraform init &&
            terraform apply -auto-approve
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        emptyDir: {}
