apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  labels:
    app: terraform
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
        - /bin/sh
        - -c
        - |
          terraform init &&
          terraform apply -auto-approve
        volumeMounts:
        - mountPath: /workspace
          name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        gitRepo:
          repository: https://github.com/moti-cohen/argo.git
          revision: main
          directory: template/ec2
