apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  namespace: default  # Specify the namespace here
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      restartPolicy: OnFailure  # Add the restart policy here
      initContainers:
        - name: git-clone
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache git &&
              git clone https://github.com/moti-cohen/argo.git /workspace &&
              ls -al /workspace
              terraform init &&
              terraform apply -auto-approve
          volumeMounts:
            - mountPath: /workspace
              name: terraform-code  # Ensure this matches the volume name
      containers:
        - name: terraform
          image: hashicorp/terraform:latest
          workingDir: /workspace/template/ec2
          command:
            - terraform
            - validate
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: terraform-code  # Define the terraform-code volume
          emptyDir: {}  # Use an emptyDir volume or another appropriate type
        - name: workspace
          emptyDir: {}
