apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
          - /bin/sh
          - -c
          - |
            sleep 1000
            echo "Contents of /workspace:" &&
            ls -al /workspace &&
            git clone https://github.com/moti-cohen/argo.git /workspace
            cd /workspace &&
            terraform init &&
            terraform apply -auto-approve
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        emptyDir: {}
