apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      initContainers:
      - name: git-clone
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - |
            apk add --no-cache git &&
            git clone https://github.com/moti-cohen/argo.git /workspace &&
            ls -al /workspace
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
          - /bin/sh
          - -c
          - |
            cd /workspace/template &&
            terraform init &&
            terraform apply -auto-approve
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        emptyDir: {}
