apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
          - /bin/sh
          - -c
          - git clone https://github.com/moti-cohen/argo.git /workspace
          - cd /workspace/template/ec2
          - terraform init -chdir=/workspace/template/ec2
          - terraform apply -auto-approve -chdir=/workspace/template/ec2
        volumeMounts:
          - mountPath: /workspace
            name: terraform-code
      restartPolicy: OnFailure
      volumes:
      - name: terraform-code
        emptyDir: {}
