apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/moti-cohen/argo.git
        revision: main  # Changed from targetRevision to revision
        files:
          - path: lambda-rds/templates/*.yaml
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/moti-cohen/argo.git
        targetRevision: HEAD
        path: 'lambda-rds'  # הנתיב ל-Helm chart שלך
        helm:
          valueFiles:
            - '{{path}}'  # שימוש בקובץ ה-values.yaml שזוהה
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true  # Ensure only out of sync resources are applied
