apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/moti-cohen/argo.git
        revision: main  # Main branch of the repo
        files:
          - path: lambda-rds/templates/*.yaml  # Path to the manifest files
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/moti-cohen/argo.git
        targetRevision: HEAD
        path: 'lambda-rds'  # Path to Helm chart or Kubernetes manifests
        helm:
          valueFiles:
            - values.yaml  # Correct reference to the values.yaml file in lambda-rds
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'  # Namespace derived from basename
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true  # Only apply out of sync resources
