{{- $filetfvar := .Files.Get "files/variables.tfvars" | sha256sum -}}
{{- $filetf := .Files.Get "files/ec2.tf" | sha256sum -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job-{{ printf "%s" $filetfvar | sha256sum | trunc 8 }}-{{ now | date "20060102-150405" }}
  annotations:
    checksum/config: "{{ printf "%s%s" $filetfvar $filetf | sha256sum }}"
spec:
  template:
    spec:
      serviceAccountName: terraform-deploy-sa
      containers:
        - name: terraform
          image: hashicorp/terraform:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              rm -f /workspace/terraform.tfstate.d/terraform.tfstate &&
              git clone https://github.com/moti-cohen/argo.git /workspace &&
              cd /workspace/files &&
              terraform init &&
              terraform plan &&
              terraform apply -auto-approve &&
    e         cho "Terraform applied successfully" || (echo "Terraform apply failed" && exit 1)
          volumeMounts:
            - mountPath: /workspace/code
              name: terraform-code
            - mountPath: /workspace/state
              name: terraform-state
      restartPolicy: OnFailure
      volumes:
        - name: terraform-state
          persistentVolumeClaim:
            claimName: terraform-state-pvc
        - name: terraform-code
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
