vpcID: "vpc-021f9a2abf0532d92"

securityGroupRDS:
  description: "Security group for RDS"
  ingressRules:
    - fromPort: 80
      toPort: 81
      ipProtocol: tcp
      cidrIP: "10.0.0.0/8"  # Specify a CIDR block instead of groupID
      description: "Allow traffic from specific CIDR range"

      

securityGroupLambda:
  name: "sg-6"
  description: "Security group for Lambda"
  ingressRules: []
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: tcp
      cidrIP: "0.0.0.0/0"

rds:
  dbInstanceIdentifier: "rds-6"
  dbInstanceClass: "db.t3.micro"
  engine: "mysql"
  engineVersion: "14"
  username: "admin"
  password: "yourpassword"
  allocatedStorage: 20
  backupRetentionPeriod: 7
  subnetGroupName: "subnet-group2"
  id: sg-0e7b261c28e9fe78e

lambda:
  functionName: "my-lambda-function"
  role: "arn:aws:iam::123456789012:role/LambdaExecutionRole"
  s3Bucket: "my-bucket"
  s3Key: "lambda-code.zip"
  handler: "index.handler"
  runtime: "nodejs14.x"
  memorySize: 128
  timeout: 10
  subnetIDs:
    - "subnet-0dd40057437e9bd30"
